AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A simple hello world REST API
Resources:
  HelloWorldApi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: handler.handler
      Runtime: nodejs6.10
      # MemorySize: 128
      # Timeout: 3
      Events:
        Endpoint:
          Type: Api
          Properties:
            Path: /helloworld
            Method: get

Outputs:
  endpoint:
    Description: The API Gateway endpoint for invoking the API
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com' 
